version: '3'

services:
  node:
    build: .
    ports:
     - 3000:3000
     - "3022:22"
    links:
      - mongo
    networks:
      - mongo-compose-network
    volumes:
      - ./work/git:/git
#      - ./work/node_modules:/usr/lib/node_modules/
    
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: thr0w
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2020!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
    ports:
      - "27017:27017"
    volumes:
      - ./work/mongodata:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
