version: '3'

services:
  dev:
    build: ./node
    ports:
     - 1234:1234
     - 3000:3000
     - 8085:8085
     - "3022:22"
    links:
      - mongo
    networks:
      - mongo-compose-network
    volumes:
      - ./work/git:/git
#      - ./work/.bashrc:/root/.bashrc
      - ./work/.config:/root/.config
      - ./work/.ssh:/root/.ssh
      - ./work/.git:/root/.git
      - ./work/.gitconfig:/root/.gitconfig
      - ./work/.npm:/root/.npm
      - ./work/.vscode-server/:/root/.vscode-server
      - ./work/ssl/:/root/ssl
#      - /etc/letsencrypt/live/cloud.hoda5.com:/root/ssl
#      - ./work/node_modules:/usr/lib/node_modules/
         
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: thr0w
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2020!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
    ports:
      - "27017:27017"
    volumes:
      - ./work/mongodata:/data/db
    networks:
      - mongo-compose-network
    command: mongod --replSet rs1 --port 27017  --oplogSize 16 
    restart: always

#  appwrite-dsv:
#    image: appwrite/install
##    ports:
##      - "3080:80"
##      - "3443:443"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./work/appwrite:/install/appwrite:rw
#    environment:
#      _APP_OPTIONS_FORCE_HTTPS: "false"

  redis:
    image: redis
    ports:
      - "6379:6379"

#  whatsapp-thr0w:
#    image: whatsapp-web-reveng
#    ports:
#      - "2019:2019"
#      - "2018:2018"

networks: 
    mongo-compose-network:
      driver: bridge

